name: Terragrunt CD

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'The directory where Terragrunt should run'
        required: true
        type: string
      terraform-version:
        description: 'Version of Terraform to use'
        required: false
        type: string
        default: '1.6.2'
    secrets:
      TERRAGRUNT_GITHUB_TOKEN:
        required: false
      GCP_SERVICE_ACCOUNT_KEY:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - name: Install Terragrunt
        run: |
          TERRAGRUNT_VERSION=$(curl -s https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | grep tag_name | cut -d '"' -f 4)
          wget https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          sudo chmod +x /usr/local/bin/terragrunt

      # - name: GCP Authentication
      #   if: secrets.GCP_SERVICE_ACCOUNT_KEY != ''
      #   run: |
      #     echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > gcp-key.json
      #     gcloud auth activate-service-account --key-file=gcp-key.json
      #     rm -f gcp-key.json

      - name: Terragrunt Init
        run: |
          cd ${{ inputs.working-directory }}
          terragrunt init
        env:
          TERRAGRUNT_GITHUB_TOKEN: ${{ secrets.TERRAGRUNT_GITHUB_TOKEN }}

      - name: Terragrunt Plan
        run: |
          cd ${{ inputs.working-directory }}
          terragrunt plan
        env:
          TERRAGRUNT_GITHUB_TOKEN: ${{ secrets.TERRAGRUNT_GITHUB_TOKEN }}

      - name: Terragrunt Apply
        run: |
          cd ${{ inputs.working-directory }}
          terragrunt apply -auto-approve
        env:
          TERRAGRUNT_GITHUB_TOKEN: ${{ secrets.TERRAGRUNT_GITHUB_TOKEN }}
