name: Terragrunt Format

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'The directory where Terragrunt should run'
        required: true
        type: string

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terragrunt
        run: |
          curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.50.0/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt

      - name: Run Terragrunt Format
        run: |
          ls -lart
          cd ${{ inputs.working-directory }}
          terragrunt fmt -recursive
          terragrunt run-all hclfmt